# **예외처리**
> - 예외가 발생하는 부분 -> try{}
> - 예외를 처리하는 부분 -> catch(){}

<br>

## **kotlin의 예외처리 방식**
kotlin에서 예외가 발생했을 때 호출 스택을 올라가면서 예외 처리가 나올 때 까지 예외를 다시 던진다.
```kotlin
fun checkPercentage(percentage: Int) {
  if (percentage !in 0..100) {
    throw IllegalArgumentException(
      "퍼센트는 0이상 100이하의 숫자여야 합니다"
    )
  }
}
```
- 인자로 받은 percentage의 값을 검사하는 함수이다. 
- kotlin에서는 예외를 던질 때 throw키워드를 사용하며 자바와 달리 new키워드를 붙이지 않는다.

<br>

![예외처리](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F7XRjz%2FbtrH31KanIv%2FkTyS2fq2fvCpYU9k6qJVwK%2Fimg.png)
-   예외가 발생하면 예외의 종류와 함께 메시지가 출력된다.

<br>

```kotlin
val percentage =
  if(number in 0..100)
    number
  else
    throw IllegalArgumentException("퍼센트는 0이상 100이하의 숫자여야 합니다")
```
- kotlin에서 throw는 식이기 때문에 다른 식에 포함될 수 있다.
- number의 값을 검사해서 범위 내에 있다면 percentage값을 number로 초기화하고 범위를 벗어난다면 예외를 던지는 코드이다.

<br>

## **try, catch, finally**
```kotlin
try {
    코드 -> 예외발생 가능한 코드
} catch(변수명 : 예외타입A){
    예외를 처리하는 코드
} catch(변수명 : 예외타입B){
    예외를 처리하는 코드
} finally{
    무조건 실행되어야 할 코드
}
```
- try문에서 A라는 예외가 발생하면 catch문에서 A라는 예외를 처리하겠다고 명시적으로 적어줘야 한다 (그렇지않으면 오류가 발생)
- 모든 종류의 예외를 포함하는 예외타입 -> Exception
- try, catch는 독립적으로 사용할 수 없다.

<br>

## **try 식으로 사용**
```kotlin
fun convertToInt(reader: BufferedReader) {
  val number = try {
    Integer.parseInt(reader.readLine())
  } catch (e: NumberFormatException) {
    return
  }
  println(number)
}
```
-  try키워드는 식이기 때문에 변수에 값을 대입할 수 있지만, 본문을 반드시 중괄호로 둘러싸야 한다.

***